#!/usr/bin/env bash
# Task: script that pings an IP address passed as an argument.

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <IP>"
    exit 1
fi

IP_ADDRESS=$1

# Ping the IP address
ping -c 4 "$IP_ADDRESS"
