#!/usr/bin/env bash
# This script will change the IP of your home network

sudo sed -i '/127.0.0.2 localhost/d' /etc/hosts
sudo sed -i '/8.8.8.8 facebook.com/d' /etc/hosts
echo -e "127.0.0.2\tlocalhost" | sudo tee -a /etc/hosts
echo -e "8.8.8.8\tfacebook.com" | sudo tee -a /etc/hosts
