#!/usr/bin/env bash
# This script configures the /etc/hosts file to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8

sudo bash -c 'echo "127.0.0.2    localhost" >> /etc/hosts'
sudo bash -c 'echo "8.8.8.8      facebook.com" >> /etc/hosts'
