#!/usr/bin/env bash
# This script configures the /etc/hosts file to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8

# Change the IP address of localhost to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Change the IP address of facebook.com to 8.8.8.8
sudo sed -i 's/facebook.com/8.8.8.8/g' /etc/hosts
